name: agaquiz
description: "Juego tipo preguntados con administrador interno de preguntas"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  beamer: ^1.6.1
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  toast: ^0.3.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  animate_do: ^3.3.4
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - pubspec.yaml
